// cmd/bench/sample_cmd.go
package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"net/http"
	"os"
	"strings"
	"time"

	"github.com/mathwro/DocuMcp/internal/bench/tasks"
)

func runSampleURLs(args []string) {
	fs := flag.NewFlagSet("sample-urls", flag.ExitOnError)
	perSource := fs.Int("per-source", 5, "max URLs per source")
	out := fs.String("out", "internal/bench/corpus/page-urls.txt", "output file")
	_ = fs.Parse(args)

	docURL := envOr("DOCUMCP_BENCH_URL", "http://127.0.0.1:8080")
	bearer := os.Getenv("DOCUMCP_API_KEY")

	sources, err := fetchSources(docURL, bearer)
	if err != nil {
		fatal("list sources: %v", err)
	}
	mcp := tasks.NewMCPClient(docURL+"/mcp", bearer)
	ctx := context.Background()

	var lines []string
	lines = append(lines, "# Generated by `bench sample-urls`. Edit freely; lines starting with # are ignored.")
	for _, src := range sources {
		urls, err := sampleURLsFromSource(ctx, mcp, src, *perSource)
		if err != nil {
			fmt.Fprintf(os.Stderr, "skip source %s: %v\n", src, err)
			continue
		}
		if len(urls) > 0 {
			lines = append(lines, "", fmt.Sprintf("# %s", src))
			lines = append(lines, urls...)
		}
	}
	if err := os.WriteFile(*out, []byte(strings.Join(lines, "\n")+"\n"), 0o644); err != nil {
		fatal("write %s: %v", *out, err)
	}
	fmt.Printf("wrote %s with URLs from %d sources\n", *out, len(sources))
}

func fetchSources(baseURL, bearer string) ([]string, error) {
	req, _ := http.NewRequest(http.MethodGet, baseURL+"/api/sources", nil)
	if bearer != "" {
		req.Header.Set("authorization", "Bearer "+bearer)
	}
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode/100 != 2 {
		return nil, fmt.Errorf("status %d", resp.StatusCode)
	}
	var raw []struct {
		Name string
	}
	if err := json.NewDecoder(resp.Body).Decode(&raw); err != nil {
		return nil, err
	}
	out := make([]string, 0, len(raw))
	for _, s := range raw {
		out = append(out, s.Name)
	}
	return out, nil
}

// sampleURLsFromSource walks browse_source for top-level sections and pulls
// up to perSource page URLs across them.
func sampleURLsFromSource(ctx context.Context, mcp *tasks.MCPClient, source string, perSource int) ([]string, error) {
	root, err := mcp.CallTool(ctx, "browse_source", map[string]any{"source": source})
	if err != nil {
		return nil, fmt.Errorf("browse root: %w", err)
	}
	sections := extractSectionNames(root)
	var urls []string
	for _, sec := range sections {
		if len(urls) >= perSource {
			break
		}
		body, err := mcp.CallTool(ctx, "browse_source", map[string]any{"source": source, "section": sec})
		if err != nil {
			continue
		}
		urls = append(urls, extractURLs(body)...)
	}
	if len(urls) > perSource {
		urls = urls[:perSource]
	}
	return urls, nil
}

// extractSectionNames pulls section names from the browse_source root response.
// browse_source returns text content; we look for lines that look like section labels.
// Operator can adjust this if it doesn't match their data — sample-urls is a one-shot
// helper, not a hot path.
func extractSectionNames(text string) []string {
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "http") {
			continue
		}
		if len(line) < 80 && !strings.Contains(line, "://") {
			out = append(out, line)
		}
	}
	return out
}

// extractURLs pulls http(s) URLs out of a browse_source page-listing response.
func extractURLs(text string) []string {
	var out []string
	for _, line := range strings.Split(text, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "http://") || strings.HasPrefix(line, "https://") {
			fields := strings.Fields(line)
			if len(fields) > 0 {
				out = append(out, fields[0])
			}
		}
	}
	return out
}
